<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Animalbreeding extends Model
{
    use HasFactory;

    protected $table = "animal_breeding";
    protected $fillable = [
        'user_id',
        'transaction_type',
        'transaction_date',
        'owner_state',
        'division_id',
        'district_id',
        'tehsil',
        'vikas_khand',
        'ower_village',
        'project',
        'animal_id',
        'dam_id',
        'sire_id',
        'animal_type',
        'animal_status',
        'animal_dob',
        'semen_type',
        'bull_id',
        'batch_no',
        'lactation_number',
        'ai_id',
        'ai_date',
        'ai_data_entry_date',
        'ai_status',
        'actual_ai_heat_no',
        'ai_type',
        'heat_start_date',
        'amount_cervical',
        'ai_center',
        'doka',
        'standing_mounted',
        'mounting_attempt',
        'vocalization',
        'mictruition',
        'swollen_vulva',
        'pd_date',
        'pd_data_entry_date',
        'pd_id',
        'pd_month',
        'pd_bull_id',
        'pd_transaction_status',
        'calving_date',
        'calving_data_entry_date',
        'calving_id',
        'calf_bull_id',
        'no_of_alves',
        'calving_ease',
        'calving_transaction_status',
        'calf_1_tag_id',
        'calf_1_gender',
        'calf_1_status',
        'calf_1_length',
        'calf_1_girth',
        'calf_1_weight',
        'calf_1_genetic_defects',
        'calf_2_tag_id',
        'calf_2_gender',
        'calf_2_status',
        'calf_2_length',
        'calf_2_girth',
        'calf_2_weight',
        'calf_2_genetic_defects',
        'treated_for_milk',
        'treated_for_ketosis',
        'treated_for_downer_syndrome',
        'retention_of_placenta',
        'prolapse',
        'colostrum_feeding',
        'cutting_of_naval_cord',
        'metabolic_disease',
        'colostrum_feeding_within',
        'tag_id',
        'species',
        'owner_name',
        'owner_gender',
        'owner_mobile_no',
    ];
}